name: deep-dive-ds
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python==3.10.16
  - pip==25.0.1
  - pandas==1.4.2
  - scipy==1.15.2
  - numpy==1.24.4
  - pycocotools==2.0.8
  - pillow==9.5.0
  - jax==0.4.35
  - jaxlib==0.4.35

  - pip:
    - setuptools==75.8.2
    - wheel==0.45.1
    - protobuf==3.19.6
    - tensorflow==2.11.0
    - tensorflow-hub==0.16.1
    - tensorflow-datasets==4.8.3
    - tensorboard==2.11.2
    - opencv-python==4.11.0.86
    - scikit-learn==1.6.1
    - graphviz==0.20.3
    - pydot==3.0.4
    - ipython==8.34.0
    - ipykernel==6.29.5
    - ipywidgets==8.1.5
    - matplotlib==3.10.1
    - seaborn==0.13.2
    - plotly==6.0.1
    - tqdm==4.67.1
    - zipp==3.21.0
    - sympy==1.13.3
    - pyampute==0.0.3
    - missingno==0.5.2
    - statsmodels==0.14.4
    - Jinja2
